### ISSUE TITLE
ombd api

### ISSUE THREAD

**Issue by OSSATMTeamjc18** [mmgleave/my-movie-watchlist#4]
getting basic info and code

**Comment by mmgleave** [comment]
- [X] add general search function
- [x] fix search function to only include a certain number of results
- [x] fix GET error, not sure where this is coming from
- [x] add nested fetch to get more info for each search result
- [X] fix so you can search more than once without refreshing page manually
- [x] fix so enter from input field also counts as clicking search
- [x] append a button for adding to watch list
- [x] fix the double click requirement
- [x] see if we can eliminate duplicate movies (compare titles?)
